class ConnectionState():
    NOT_CONNECTED = 0
    CONNECTED = 1
    TRADE_CENTER = 2
    COLOSSEUM = 3


class TradeCenterState():
    CHOOSING_TRADE = 0
    CONFIRMING_TRADE = 1

class InitDataState():
    INIT = 0
    READY_TO_GO = 1
    SEEN_FIRST_WAIT = 2
    SENDING_RANDOM_DATA = 3
    WAITING_TO_SEND_DATA = 4
    START_SENDING_DATA = 5
    SENDING_DATA = 6
    TRADE_CENTER = 7
    COLOSSEUM = 8


class Com():
    BLANK = 0x00
    ITEM_1_HIGHLIGHTED = 0xD0
    ITEM_2_HIGHLIGHTED = 0xD1
    ITEM_3_HIGHLIGHTED = 0xD2
    ITEM_1_SELECTED = 0xD4
    ITEM_2_SELECTED = 0xD5
    ITEM_3_SELECTED = 0xD6

    MASTER = 0x01
    SLAVE = 0x02
    CONNECTED = 0x60
    WAIT = 0x7F

    ACTION = 0x60

    TRADE_CENTER_SELECTED = ITEM_1_SELECTED
    COLOSSEUM_SELECTED = ITEM_2_SELECTED
    BREAK_LINK = ITEM_3_SELECTED

    TRADE_CENTER_WAIT = 0xFD

    WAIT = 0xF0

    ATTACK_MOVE_1 = 0x60
    ATTACK_MOVE_2 = 0x61
    ATTACK_MOVE_3 = 0x62
    ATTACK_MOVE_4 = 0x63

    SWITCH_POKEMON_1 = 0x64
    SWITCH_POKEMON_2 = 0x65
    SWITCH_POKEMON_3 = 0x66
    SWITCH_POKEMON_4 = 0x67
    SWITCH_POKEMON_5 = 0x68
    SWITCH_POKEMON_6 = 0x69

    ATTACK_USE_STRUGGLE = 0x6E