import random

class Move():
    def __init__(self, name, hex):
        self.name = name
        self.hex = hex

    def __str__(self):
        return self.name

    @staticmethod
    def fromBytes(hex):
        return Move.reverse[hex]

    @staticmethod
    def buildReverse():
        reverse = {}
        Move.members = [attr for attr in dir(Move) if not callable(getattr(Move, attr)) and not attr.startswith("__")]
        for member in Move.members:
            move = getattr(Move, member)
            reverse[move.hex] = move

        Move.reverse = reverse

    @staticmethod
    def rnd():
        return getattr(Move, random.choice(Move.members))

Move.NOTHING = Move("Nothing", 0x00)
Move.POUND = Move("Pound", 0x01)
Move.KARATE_CHOP = Move("Karate Chop", 0x02)
Move.DOUBLE_SLAP = Move("Double Slap", 0x03)
Move.COMET_PUNCH = Move("Comet Punch", 0x04)
Move.MEGA_PUNCH = Move("Mega Punch", 0x05)
Move.PAY_DAY = Move("Pay Day", 0x06)
Move.FIRE_PUNCH = Move("Fire Punch", 0x07)
Move.ICE_PUNCH = Move("Ice Punch", 0x08)
Move.THUNDER_PUNCH = Move("Thunder Punch ", 0x09)
Move.GUST = Move("Gust", 0x10)
Move.WING_ATTACK = Move("Wing Attack", 0x11)
Move.WHIRLWIND = Move("Whirlwind", 0x12)
Move.FLY = Move("Fly", 0x13)
Move.BIND = Move("Bind", 0x14)
Move.SLAM = Move("Slam", 0x15)
Move.VINE_WHIP = Move("Vine Whip", 0x16)
Move.STOMP = Move("Stomp", 0x17)
Move.DOUBLE_KICK = Move("Double Kick", 0x18)
Move.MEGA_KICK = Move("Mega KIck", 0x19)
Move.JUMP_K_ICK = Move("Jump KIck", 0x1A)
Move.ROLLING_KICK = Move("RollingKick", 0x1B)
Move.SAND_ATTACK = Move("Sand Attack", 0x1C)
Move.HEADBUTT = Move("Headbutt", 0x1D)
Move.HORN_ATTACK = Move("Horn Attack", 0x1E)
Move.FURY_ATTACK = Move("Fury Attack", 0x1F)
Move.HORN_DRILL = Move("Horn Drill", 0x20)
Move.TACKLE = Move("Tackle", 0x21)
Move.BODYSLAM = Move("Bodyslam", 0x22)
Move.WRAP = Move("Wrap", 0x23)
Move.TAKE_DOWN = Move("Take Down ", 0x24)
Move.TRASH = Move("Trash", 0x25)
Move.DOUBLE_EDGE = Move("Double Edge", 0x26)
Move.TAIL_WHIP = Move("Tail Whip", 0x27)
Move.POISON_STING = Move("Poison Sting", 0x28)
Move.TWIN_NEEDLE = Move("Twin Needle", 0x29)
Move.PIN_MISSLE = Move("Pin Missle", 0x2A)
Move.LEER = Move("Leer", 0x2B)
Move.BITE = Move("Bite", 0x2C)
Move.GROWL = Move("Growl", 0x2D)
Move.ROAR = Move("Roar", 0x2E)
Move.SUPER_SONIC = Move("SuperSonic", 0x2F)
Move.SONIC_BOOM = Move("Sonic Boom", 0x30)
Move.DISABLE = Move("Disable", 0x32)
Move.ACID = Move("Acid", 0x33)
Move.EMBER = Move("Ember", 0x34)
Move.FLAME_THROWER = Move("FlameThrower", 0x35)
Move.MIST = Move("Mist", 0x36)
Move.WATER_GUN = Move("Water Gun", 0x37)
Move.HYDRO_PUMP = Move("Hydro Pump", 0x38)
Move.SURF = Move("Surf", 0x39)
Move.ICE_BEAM = Move("Ice Beam", 0x3A)
Move.BLIZZARD = Move("Blizzard", 0x3B)
Move.PSY_BEAM = Move("PsyBeam", 0x3C)
Move.BUBBLE_BEAM = Move("Bubble Beam", 0x3D)
Move.AURORA_BEAM = Move("Aurora Beam", 0x3E)
Move.HYPER_BEAM = Move("Hyper Beam", 0x3F)
Move.PECK = Move("Peck", 0x40)
Move.DRILL_PECK = Move("Drill Peck", 0x41)
Move.SUBMISSION = Move("Submission", 0x42)
Move.LOW_KICK = Move("Low Kick", 0x43)
Move.COUNTER = Move("Counter", 0x44)
Move.SESMIC_TOSS = Move("Sesmic Toss", 0x45)
Move.STRENGTH = Move("Strength", 0x46)
Move.ABSORB = Move("Absorb", 0x47)
Move.MEGA_DRAIN = Move("Mega Drain", 0x48)
Move.LEECH_SEED = Move("Leech Seed", 0x49)
Move.GROWTH = Move("Growth", 0x4A)
Move.RAZOR_WIND = Move("Razor Wind", 0x4B)
Move.SOLAR_BEAM = Move("Solar Beam", 0x4C)
Move.POISON_POWDER = Move("Poison Powder", 0x4D)
Move.STUN_SPORE = Move("Stun Spore", 0x4E)
Move.SLEEP_POWDER = Move("Sleep Powder", 0x4F)
Move.PETAL_DANCE = Move("Petal Dance", 0x50)
Move.STRING_SHOT = Move("String Shot", 0x51)
Move.DRAGON_RAGE = Move("Dragon Rage", 0x52)
Move.FIRE_SPIN = Move("Fire Spin", 0x53)
Move.THUNDER_SHOCK = Move("ThunderShock", 0x54)
Move.THUNDER_BOLT = Move("ThunderBolt", 0x55)
Move.THUNDER_WAVE = Move("ThunderWave", 0x56)
Move.THUNDER = Move("Thunder", 0x57)
Move.ROCK_THROW = Move("Rock Throw", 0x58)
Move.EARTH_QUAKE = Move("EarthQuake", 0x59)
Move.FISSURE = Move("Fissure", 0x5A)
Move.DIG = Move("Dig", 0x5B)
Move.TOXIC = Move("Toxic", 0x5C)
Move.CONFUSION = Move("Confusion", 0x5D)
Move.PSYCHIC = Move("Psychic", 0x5E)
Move.HYPNOSIS = Move("Hypnosis", 0x5F)
Move.MEDITATE = Move("Meditate", 0x60)
Move.AGILITY = Move("Agility", 0x61)
Move.QUICK_ATTACK = Move("Quick Attack", 0x62)
Move.RAGE = Move("Rage", 0x63)
Move.TELEPORT = Move("Teleport", 0x64)
Move.NIGHT_SHADE = Move("Night Shade", 0x65)
Move.MIMIC = Move("Mimic", 0x66)
Move.SCREECH = Move("Screech", 0x67)
Move.DOUBLE_TEAM = Move("Double Team", 0x68)
Move.RECOVER = Move("Recover", 0x69)
Move.HARDEN = Move("Harden", 0x6A)
Move.MINIMIZED = Move("Minimized", 0x6B)
Move.SMOKE_SCREEN = Move("Smoke Screen", 0x6C)
Move.CONFUSE_RAY = Move("Confuse Ray", 0x6D)
Move.WITH_DRAW = Move("WithDraw", 0x6E)
Move.DEFENCE_CURL = Move("Defence Curl", 0x6F)
Move.BARRIER = Move("Barrier", 0x70)
Move.LIGHTSCREEN = Move("Light screen", 0x71)
Move.HAZE = Move("Haze", 0x72)
Move.REFLECT = Move("Reflect", 0x73)
Move.FOCUS = Move("Focus", 0x74)
Move.BIDE = Move("Bide", 0x75)
Move.METRONOME = Move("Metronome", 0x76)
Move.MIRROR_MOVE = Move("Mirror Move", 0x77)
Move.SELF_DESTRUCT = Move("Self Destruct", 0x78)
Move.EGG_BOMB = Move("Egg Bomb", 0x79)
Move.LICK = Move("Lick", 0x7A)
Move.SMOG = Move("Smog", 0x7B)
Move.SLUDGE = Move("Sludge", 0x7C)
Move.BONE_CLUB = Move("Bone Club", 0x7D)
Move.FIRE_BLAST = Move("Fire Blast", 0x7E)
Move.WATERFALL = Move("Waterfall", 0x7F)
Move.CLAMP = Move("Clamp", 0x80)
Move.SWIFT = Move("Swift", 0x81)
Move.SKULL_BASH = Move("Skull Bash", 0x82)
Move.SPIKE_CANNON = Move("Spike Cannon", 0x83)
Move.CONSTRICT = Move("Constrict", 0x84)
Move.AMNESIA = Move("Amnesia", 0x85)
Move.KINESIS = Move("Kinesis", 0x86)
Move.SOFTBOILED = Move("Softboiled", 0x87)
Move.HI_JUMP_KICK = Move("Hi-Jump Kick", 0x88)
Move.GLARE = Move("Glare", 0x89)
Move.DREAM_EATER = Move("Dream Eater", 0x8A)
Move.POISON_GAS = Move("Poison Gas", 0x8B)
Move.BARRAGE = Move("Barrage", 0x8C)
Move.LEECH_LIFE = Move("Leech Life", 0x8D)
Move.LOVELY_KISS = Move("Lovely Kiss", 0x8E)
Move.SKY_ATTACK = Move("Sky Attack", 0x8F)
Move.TRANSFORM = Move("Transform", 0x90)
Move.BUBBLE = Move("Bubble", 0x91)
Move.DIZZY_PUNCH = Move("Dizzy Punch", 0x92)
Move.SPORE = Move("Spore", 0x93)
Move.FLASH = Move("Flash", 0x94)
Move.PSYWAVE = Move("Psywave", 0x95)
Move.SPLASH = Move("Splash", 0x96)
Move.ACID_ARMOR = Move("Acid Armor", 0x97)
Move.CRABHAMMER = Move("Crabhammer", 0x98)
Move.EXPLOSION = Move("Explosion", 0x99)
Move.FURY_SWIPE = Move("Fury Swipe", 0x9A)
Move.BONEMERANG = Move("Bonemerang", 0x9B)
Move.REST = Move("Rest", 0x9C)
Move.ROCK_SLIDE = Move("Rock Slide", 0x9D)
Move.HYPER_FANG = Move("Hyper Fang", 0x9E)
Move.SHARPEN = Move("Sharpen", 0x9F)
Move.CONVERSION = Move("Conversion", 0xA0)
Move.TRI_ATTACK = Move("Tri Attack", 0xA1)
Move.SUPER_FANG = Move("Super Fang", 0xA2)
Move.SLASH = Move("Slash", 0xA3)
Move.SUBSTITUTE = Move("Substitute", 0xA4)
Move.STRUGGLE = Move("Struggle", 0xA5)

Move.buildReverse()
