import re

input = [
    'MasterBall("0x01", "Master Ball"),',
    'UltraBall("0x02", "Ultra Ball"),',
    'BrightPowder("0x03", "BrightPowder"),',
    'GreatBall("0x04", "Great Ball"),',
    'PokeBall("0x05", "Poke Ball"),',
    'Bicycle("0x06", "Bicycle"),',
    'MoonStone("0x08", "Moon Stone"),',
    'Antidote("0x09", "Antidote"),',
    'BurnHeal("0x0A", "Burn Heal"),',
    'IceHeal("0x0B", "Ice Heal"),',
    'Awakening("0x0C", "Awakening"),',
    'ParlyzHeal("0x0D", "Parlyz Heal"),',
    'FullRestore("0x0E", "Full Restore"),',
    'MaxPotion("0x0F", "Max Potion"),',
    'HyperPotion("0x10", "Hyper Potion"),',
    'SuperPotion("0x11", "Super Potion"),',
    'Potion("0x12", "Potion"),',
    'EscapeRope("0x13", "Escape Rope"),',
    'Repel("0x14", "Repel"),',
    'MaxElixer("0x15", "Max Elixer"),',
    'FireStone("0x16", "Fire Stone"),',
    'ThunderStone("0x17", "Thunder Stone"),',
    'WaterStone("0x18", "Water Stone"),',
    'HPUp("0x1A", "HP Up"),',
    'Protein("0x1B", "Protein"),',
    'Iron("0x1C", "Iron"),',
    'Carbos("0x1D", "Carbos"),',
    'LuckyPunch("0x1E", "Lucky Punch"),',
    'Calcium("0x1F", "Calcium"),',
    'RareCandy("0x20", "Rare Candy"),',
    'XAccuracy("0x21", "X Accuracy"),',
    'LeafStone("0x22", "Leaf Stone"),',
    'MetalPowder("0x23", "Metal Powder"),',
    'Nugget("0x24", "Nugget"),',
    'PokeDoll("0x25", "Poke Doll"),',
    'FullHeal("0x26", "Full Heal"),',
    'Revive("0x27", "Revive"),',
    'MaxRevive("0x28", "Max Revive"),',
    'GuardSpec("0x29", "Guard Spec."),',
    'SuperRepel("0x2A", "Super Repel"),',
    'MaxRepel("0x2B", "Max Repel"),',
    'DireHit("0x2C", "Dire Hit"),',
    'FreshWater("0x2E", "Fresh Water"),',
    'SodaPop("0x2F", "Soda Pop"),',
    'Lemonade("0x30", "Lemonade"),',
    'XAttack("0x31", "X Attack"),',
    'XDefend("0x33", "X Defend"),',
    'XSpeed("0x34", "X Speed"),',
    'XSpecial("0x35", "X Special"),',
    'CoinCase("0x36", "Coin Case"),',
    'Itemfinder("0x37", "Itemfinder"),',
    'ExpShare("0x39", "Exp Share"),',
    'OldRod("0x3A", "Old Rod"),',
    'GoodRod("0x3B", "Good Rod"),',
    'SilverLeaf("0x3C", "Silver Leaf"),',
    'SuperRod("0x3D", "Super Rod"),',
    'PPUp("0x3E", "PP Up"),',
    'Ether("0x3F", "Ether"),',
    'MaxEther("0x40", "Max Ether"),',
    'Elixer("0x41", "Elixer"),',
    'RedScale("0x42", "Red Scale"),',
    'SecretPotion("0x43", "SecretPotion"),',
    'SSTicket("0x44", "S.S. Ticket"),',
    'MysteryEgg("0x45", "Mystery Egg"),',
    'ClearBell("0x46", "Clear Bell*"),',
    'SilverWing("0x47", "Silver Wing"),',
    'MoomooMilk("0x48", "Moomoo Milk"),',
    'QuickClaw("0x49", "Quick Claw"),',
    'PSNCureBerry("0x4A", "PSNCureBerry"),',
    'GoldLeaf("0x4B", "Gold Leaf"),',
    'SoftSand("0x4C", "Soft Sand"),',
    'SharpBeak("0x4D", "Sharp Beak"),',
    'PRZCureBerry("0x4E", "PRZCureBerry"),',
    'BurntBerry("0x4F", "Burnt Berry"),',
    'IceBerry("0x50", "Ice Berry"),',
    'PoisonBarb("0x51", "Poison Barb"),',
    'KingsRock("0x52", "King\'s Rock"),',
    'BitterBerry("0x53", "Bitter Berry"),',
    'MintBerry("0x54", "Mint Berry"),',
    'RedApricorn("0x55", "Red Apricorn"),',
    'TinyMushroom("0x56", "TinyMushroom"),',
    'BigMushroom("0x57", "Big Mushroom"),',
    'SilverPowder("0x58", "SilverPowder"),',
    'BluApricorn("0x59", "Blu Apricorn"),',
    'AmuletCoin("0x5B", "Amulet Coin"),',
    'YlwApricorn("0x5C", "Ylw Apricorn"),',
    'GrnApricorn("0x5D", "Grn Apricorn"),',
    'CleanseTag("0x5E", "Cleanse Tag"),',
    'MysticWater("0x5F", "Mystic Water"),',
    'TwistedSpoon("0x60", "TwistedSpoon"),',
    'WhtApricorn("0x61", "Wht Apricorn"),',
    'BlackBelt("0x62", "Black Belt"),',
    'BlkApricorn("0x63", "Blk Apricorn"),',
    'PnkApricorn("0x65", "Pnk Apricorn"),',
    'BlackGlasses("0x66", "BlackGlasses"),',
    'SlowpokeTail("0x67", "SlowpokeTail"),',
    'PinkBow("0x68", "Pink Bow"),',
    'Stick("0x69", "Stick"),',
    'SmokeBall("0x6A", "Smoke Ball"),',
    'NeverMeltIce("0x6B", "NeverMeltIce"),',
    'Magnet("0x6C", "Magnet"),',
    'MiracleBerry("0x6D", "MiracleBerry"),',
    'Pearl("0x6E", "Pearl"),',
    'BigPearl("0x6F", "Big Pearl"),',
    'Everstone("0x70", "Everstone"),',
    'SpellTag("0x71", "Spell Tag"),',
    'RageCandyBar("0x72", "RageCandyBar"),',
    'GSBall("0x73", "GS Ball*"),',
    'BlueCard("0x74", "Blue Card*"),',
    'MiracleSeed("0x75", "Miracle Seed"),',
    'ThickClub("0x76", "Thick Club"),',
    'FocusBand("0x77", "Focus Band"),',
    'EnergyPowder("0x79", "EnergyPowder"),',
    'EnergyRoot("0x7A", "Energy Root"),',
    'HealPowder("0x7B", "Heal Powder"),',
    'RevivalHerb("0x7C", "Revival Herb"),',
    'HardStone("0x7D", "Hard Stone"),',
    'LuckyEgg("0x7E", "Lucky Egg"),',
    'CardKey("0x7F", "Card Key"),',
    'MachinePart("0x80", "Machine Part"),',
    'EggTicket("0x81", "Egg Ticket*"),',
    'LostItem("0x82", "Lost Item"),',
    'Stardust("0x83", "Stardust"),',
    'StarPiece("0x84", "Star Piece"),',
    'BasementKey("0x85", "Basement Key"),',
    'Pass("0x86", "Pass"),',
    'Charcoal("0x8A", "Charcoal"),',
    'BerryJuice("0x8B", "Berry Juice"),',
    'ScopeLens("0x8C", "Scope Lens"),',
    'MetalCoat("0x8F", "Metal Coat"),',
    'DragonFang("0x90", "Dragon Fang"),',
    'Leftovers("0x92", "Leftovers"),',
    'MysteryBerry("0x96", "MysteryBerry"),',
    'DragonScale("0x97", "Dragon Scale"),',
    'BerserkGene("0x98", "Berserk Gene"),',
    'SacredAsh("0x9C", "Sacred Ash"),',
    'HeavyBall("0x9D", "Heavy Ball"),',
    'FlowerMail("0x9E", "Flower Mail"),',
    'LevelBall("0x9F", "Level Ball"),',
    'LureBall("0xA0", "Lure Ball"),',
    'FastBall("0xA1", "Fast Ball"),',
    'LightBall("0xA3", "Light Ball"),',
    'FriendBall("0xA4", "Friend Ball"),',
    'MoonBall("0xA5", "Moon Ball"),',
    'LoveBall("0xA6", "Love Ball"),',
    'NormalBox("0xA7", "Normal Box"),',
    'GorgeousBox("0xA8", "Gorgeous Box"),',
    'SunStone("0xA9", "Sun Stone"),',
    'PolkadotBow("0xAA", "Polkadot Bow"),',
    'UpGrade("0xAC", "Up-Grade"),',
    'Berry("0xAD", "Berry"),',
    'GoldBerry("0xAE", "Gold Berry"),',
    'SquirtBottle("0xAF", "SquirtBottle"),',
    'ParkBall("0xB1", "Park Ball"),',
    'RainbowWing("0xB2", "Rainbow Wing"),',
    'BrickPiece("0xB4", "Brick Piece"),',
    'SurfMail("0xB5", "Surf Mail"),',
    'Litebluemail("0xB6", "Litebluemail"),',
    'Portraitmail("0xB7", "Portraitmail"),',
    'LovelyMail("0xB8", "Lovely Mail"),',
    'EonMail("0xB9", "Eon Mail"),',
    'MorphMail("0xBA", "Morph Mail"),',
    'BlueskyMail("0xBB", "Bluesky Mail"),',
    'MusicMail("0xBC", "Music Mail"),',
    'MirageMail("0xBD", "Mirage Mail"),',
    'TM01("0xBF", "TM01"),',
    'TM02("0xC0", "TM02"),',
    'TM03("0xC1", "TM03"),',
    'TM04("0xC2", "TM04"),',
    'TM05("0xC4", "TM05"),',
    'TM06("0xC5", "TM06"),',
    'TM07("0xC6", "TM07"),',
    'TM08("0xC7", "TM08"),',
    'TM09("0xC8", "TM09"),',
    'TM10("0xC9", "TM10"),',
    'TM11("0xCA", "TM11"),',
    'TM12("0xCB", "TM12"),',
    'TM13("0xCC", "TM13"),',
    'TM14("0xCD", "TM14"),',
    'TM15("0xCE", "TM15"),',
    'TM16("0xCF", "TM16"),',
    'TM17("0xD0", "TM17"),',
    'TM18("0xD1", "TM18"),',
    'TM19("0xD2", "TM19"),',
    'TM20("0xD3", "TM20"),',
    'TM21("0xD4", "TM21"),',
    'TM22("0xD5", "TM22"),',
    'TM23("0xD6", "TM23"),',
    'TM24("0xD7", "TM24"),',
    'TM25("0xD8", "TM25"),',
    'TM26("0xD9", "TM26"),',
    'TM27("0xDA", "TM27"),',
    'TM28("0xDB", "TM28"),',
    'TM29("0xDD", "TM29"),',
    'TM30("0xDE", "TM30"),',
    'TM31("0xDF", "TM31"),',
    'TM32("0xE0", "TM32"),',
    'TM33("0xE1", "TM33"),',
    'TM34("0xE2", "TM34"),',
    'TM35("0xE3", "TM35"),',
    'TM36("0xE4", "TM36"),',
    'TM37("0xE5", "TM37"),',
    'TM38("0xE6", "TM38"),',
    'TM39("0xE7", "TM39"),',
    'TM40("0xE8", "TM40"),',
    'TM41("0xE9", "TM41"),',
    'TM42("0xEA", "TM42"),',
    'TM43("0xEB", "TM43"),',
    'TM44("0xEC", "TM44"),',
    'TM45("0xED", "TM45"),',
    'TM46("0xEE", "TM46"),',
    'TM47("0xEF", "TM47"),',
    'TM48("0xF0", "TM48"),',
    'TM49("0xF1", "TM49"),',
    'TM50("0xF2", "TM50"),',
    'HM01("0xF3", "HM01"),',
    'HM02("0xF4", "HM02"),',
    'HM03("0xF5", "HM03"),',
    'HM04("0xF6", "HM04"),',
    'HM05("0xF7", "HM05"),',
    'HM06("0xF8", "HM06"),',
    'HM07("0xF9", "HM07"),',
    'HM08("0xFA", "HM08"),',
    'HM09("0xFB", "HM09"),',
    'HM10("0xFC", "HM10"),',
    'HM11("0xFD", "HM11"),',
    'HM12("0xFE", "HM12")'
]

input2 = [
    'Nothing("0x00", "Nothing"),',
    'Pound("0x01", "Pound"),',
    'KarateChop("0x02", "Karate Chop"),',
    'DoubleSlap("0x03", "Double Slap"),',
    'CometPunch("0x04", "Comet Punch"),',
    'MegaPunch("0x05", "Mega Punch"),',
    'PayDay("0x06", "Pay Day"),',
    'FirePunch("0x07", "Fire Punch"),',
    'IcePunch("0x08", "Ice Punch"),',
    'ThunderPunch("0x09", "Thunder Punch "),',
    'Gust("0x10", "Gust"),',
    'WingAttack("0x11", "Wing Attack"),',
    'Whirlwind("0x12", "Whirlwind"),',
    'Fly("0x13", "Fly"),',
    'Bind("0x14", "Bind"),',
    'Slam("0x15", "Slam"),',
    'VineWhip("0x16", "Vine Whip"),',
    'Stomp("0x17", "Stomp"),',
    'DoubleKick("0x18", "Double Kick"),',
    'MegaKick("0x19", "Mega KIck"),',
    'JumpKIck("0x1A", "Jump KIck"),',
    'RollingKick("0x1B", "RollingKick"),',
    'SandAttack("0x1C", "Sand Attack"),',
    'Headbutt("0x1D", "Headbutt"),',
    'HornAttack("0x1E", "Horn Attack"),',
    'FuryAttack("0x1F", "Fury Attack"),',
    'HornDrill("0x20", "Horn Drill"),',
    'Tackle("0x21", "Tackle"),',
    'Bodyslam("0x22", "Bodyslam"),',
    'Wrap("0x23", "Wrap"),',
    'TakeDown("0x24", "Take Down "),',
    'Trash("0x25", "Trash"),',
    'DoubleEdge("0x26", "Double Edge"),',
    'TailWhip("0x27", "Tail Whip"),',
    'PoisonSting("0x28", "Poison Sting"),',
    'TwinNeedle("0x29", "Twin Needle"),',
    'PinMissle("0x2A", "Pin Missle"),',
    'Leer("0x2B", "Leer"),',
    'Bite("0x2C", "Bite"),',
    'Growl("0x2D", "Growl"),',
    'Roar("0x2E", "Roar"),',
    'SuperSonic("0x2F", "SuperSonic"),',
    'SonicBoom("0x30", "Sonic Boom"),',
    'Disable("0x32", "Disable"),',
    'Acid("0x33", "Acid"),',
    'Ember("0x34", "Ember"),',
    'FlameThrower("0x35", "FlameThrower"),',
    'Mist("0x36", "Mist"),',
    'WaterGun("0x37", "Water Gun"),',
    'HydroPump("0x38", "Hydro Pump"),',
    'Surf("0x39", "Surf"),',
    'IceBeam("0x3A", "Ice Beam"),',
    'Blizzard("0x3B", "Blizzard"),',
    'PsyBeam("0x3C", "PsyBeam"),',
    'BubbleBeam("0x3D", "Bubble Beam"),',
    'AuroraBeam("0x3E", "Aurora Beam"),',
    'HyperBeam("0x3F", "Hyper Beam"),',
    'Peck("0x40", "Peck"),',
    'DrillPeck("0x41", "Drill Peck"),',
    'Submission("0x42", "Submission"),',
    'LowKick("0x43", "Low Kick"),',
    'Counter("0x44", "Counter"),',
    'SesmicToss("0x45", "Sesmic Toss"),',
    'Strength("0x46", "Strength"),',
    'Absorb("0x47", "Absorb"),',
    'MegaDrain("0x48", "Mega Drain"),',
    'LeechSeed("0x49", "Leech Seed"),',
    'Growth("0x4A", "Growth"),',
    'RazorWind("0x4B", "Razor Wind"),',
    'SolarBeam("0x4C", "Solar Beam"),',
    'PoisonPowder("0x4D", "Poison Powder"),',
    'StunSpore("0x4E", "Stun Spore"),',
    'SleepPowder("0x4F", "Sleep Powder"),',
    'PetalDance("0x50", "Petal Dance"),',
    'StringShot("0x51", "String Shot"),',
    'DragonRage("0x52", "Dragon Rage"),',
    'FireSpin("0x53", "Fire Spin"),',
    'ThunderShock("0x54", "ThunderShock"),',
    'ThunderBolt("0x55", "ThunderBolt"),',
    'ThunderWave("0x56", "ThunderWave"),',
    'Thunder("0x57", "Thunder"),',
    'RockThrow("0x58", "Rock Throw"),',
    'EarthQuake("0x59", "EarthQuake"),',
    'Fissure("0x5A", "Fissure"),',
    'Dig("0x5B", "Dig"),',
    'Toxic("0x5C", "Toxic"),',
    'Confusion("0x5D", "Confusion"),',
    'Psychic("0x5E", "Psychic"),',
    'Hypnosis("0x5F", "Hypnosis"),',
    'Meditate("0x60", "Meditate"),',
    'Agility("0x61", "Agility"),',
    'QuickAttack("0x62", "Quick Attack"),',
    'Rage("0x63", "Rage"),',
    'Teleport("0x64", "Teleport"),',
    'NightShade("0x65", "Night Shade"),',
    'Mimic("0x66", "Mimic"),',
    'Screech("0x67", "Screech"),',
    'DoubleTeam("0x68", "Double Team"),',
    'Recover("0x69", "Recover"),',
    'Harden("0x6A", "Harden"),',
    'Minimized("0x6B", "Minimized"),',
    'SmokeScreen("0x6C", "Smoke Screen"),',
    'ConfuseRay("0x6D", "Confuse Ray"),',
    'WithDraw("0x6E", "WithDraw"),',
    'DefenceCurl("0x6F", "Defence Curl"),',
    'Barrier("0x70", "Barrier"),',
    'Lightscreen("0x71", "Light screen"),',
    'Haze("0x72", "Haze"),',
    'Reflect("0x73", "Reflect"),',
    'Focus("0x74", "Focus"),',
    'Bide("0x75", "Bide"),',
    'Metronome("0x76", "Metronome"),',
    'MirrorMove("0x77", "Mirror Move"),',
    'SelfDestruct("0x78", "Self Destruct"),',
    'EggBomb("0x79", "Egg Bomb"),',
    'Lick("0x7A", "Lick"),',
    'Smog("0x7B", "Smog"),',
    'Sludge("0x7C", "Sludge"),',
    'BoneClub("0x7D", "Bone Club"),',
    'FireBlast("0x7E", "Fire Blast"),',
    'Waterfall("0x7F", "Waterfall"),',
    'Clamp("0x80", "Clamp"),',
    'Swift("0x81", "Swift"),',
    'SkullBash("0x82", "Skull Bash"),',
    'SpikeCannon("0x83", "Spike Cannon"),',
    'Constrict("0x84", "Constrict"),',
    'Amnesia("0x85", "Amnesia"),',
    'Kinesis("0x86", "Kinesis"),',
    'Softboiled("0x87", "Softboiled"),',
    'HiJumpKick("0x88", "Hi-Jump Kick"),',
    'Glare("0x89", "Glare"),',
    'DreamEater("0x8A", "Dream Eater"),',
    'PoisonGas("0x8B", "Poison Gas"),',
    'Barrage("0x8C", "Barrage"),',
    'LeechLife("0x8D", "Leech Life"),',
    'LovelyKiss("0x8E", "Lovely Kiss"),',
    'SkyAttack("0x8F", "Sky Attack"),',
    'Transform("0x90", "Transform"),',
    'Bubble("0x91", "Bubble"),',
    'DizzyPunch("0x92", "Dizzy Punch"),',
    'Spore("0x93", "Spore"),',
    'Flash("0x94", "Flash"),',
    'Psywave("0x95", "Psywave"),',
    'Splash("0x96", "Splash"),',
    'AcidArmor("0x97", "Acid Armor"),',
    'Crabhammer("0x98", "Crabhammer"),',
    'Explosion("0x99", "Explosion"),',
    'FurySwipe("0x9A", "Fury Swipe"),',
    'Bonemerang("0x9B", "Bonemerang"),',
    'Rest("0x9C", "Rest"),',
    'RockSlide("0x9D", "Rock Slide"),',
    'HyperFang("0x9E", "Hyper Fang"),',
    'Sharpen("0x9F", "Sharpen"),',
    'Conversion("0xA0", "Conversion"),',
    'TriAttack("0xA1", "Tri Attack"),',
    'SuperFang("0xA2", "Super Fang"),',
    'Slash("0xA3", "Slash"),',
    'Substitute("0xA4", "Substitute"),',
    'Struggle("0xA5", "Struggle"),'
]

input3 = [
    'Rhydon("0x01", "Rhydon")',
    'Kangaskhan("0x02", "Kangaskhan")',
    'NidoranM("0x03", "Nidoran M")',
    'Clefairy("0x04", "Clefairy")',
    'Spearow("0x05", "Spearow")',
    'Voltorb("0x06", "Voltorb")',
    'Nidoking("0x07", "Nidoking")',
    'Slowbro("0x08", "Slowbro")',
    'Ivysaur("0x09", "Ivysaur")',
    'Exeggutor("0x0A", "Exeggutor")',
    'Lickitung("0x0B", "Lickitung")',
    'Exeggcute("0x0C", "Exeggcute")',
    'Grimer("0x0D", "Grimer")',
    'Gengar("0x0E", "Gengar")',
    'NidoranF("0x0F", "Nidoran F")',
    'Nidoqueen("0x10", "Nidoqueen")',
    'Cubone("0x11", "Cubone")',
    'Rhyhorn("0x12", "Rhyhorn")',
    'Lapras("0x13", "Lapras")',
    'Arcanine("0x14", "Arcanine")',
    'Mew("0x15", "Mew")',
    'Gyarados("0x16", "Gyarados")',
    'Shellder("0x17", "Shellder")',
    'Tentacool("0x18", "Tentacool")',
    'Gastly("0x19", "Gastly")',
    'Scyther("0x1A", "Scyther")',
    'Staryu("0x1B", "Staryu")',
    'Blastoise("0x1C", "Blastoise")',
    'Pinsir("0x1D", "Pinsir")',
    'Tangela("0x1E", "Tangela")',
    'Growlithe("0x21", "Growlithe")',
    'Onix("0x22", "Onix")',
    'Fearow("0x23", "Fearow")',
    'Pidgey("0x24", "Pidgey")',
    'Slowpoke("0x25", "Slowpoke")',
    'Kadabra("0x26", "Kadabra")',
    'Graveler("0x27", "Graveler")',
    'Chansey("0x28", "Chansey")',
    'Machoke("0x29", "Machoke")',
    'MrMime("0x2A", "Mr. Mime")',
    'Hitmonlee("0x2B", "Hitmonlee")',
    'Hitmonchan("0x2C", "Hitmonchan")',
    'Arbok("0x2D", "Arbok")',
    'Parasect("0x2E", "Parasect")',
    'Psyduck("0x2F", "Psyduck")',
    'Drowzee("0x30", "Drowzee")',
    'Golem("0x31", "Golem")',
    'Magmar("0x33", "Magmar")',
    'Electabuzz("0x35", "Electabuzz")',
    'Magneton("0x36", "Magneton")',
    'Koffing("0x37", "Koffing")',
    'Mankey("0x39", "Mankey")',
    'Seel("0x3A", "Seel")',
    'Diglett("0x3B", "Diglett")',
    'Tauros("0x3C", "Tauros")',
    'Farfetchd("0x40", "Farfetch\'d")',
    'Venonat("0x41", "Venonat")',
    'Dragonite("0x42", "Dragonite")',
    'Doduo("0x46", "Doduo")',
    'Poliwag("0x47", "Poliwag")',
    'Jynx("0x48", "Jynx")',
    'Moltres("0x49", "Moltres")',
    'Articuno("0x4A", "Articuno")',
    'Zapdos("0x4B", "Zapdos")',
    'Ditto("0x4C", "Ditto")',
    'Meowth("0x4D", "Meowth")',
    'Krabby("0x4E", "Krabby")',
    'Vulpix("0x52", "Vulpix")',
    'Ninetales("0x53", "Ninetales")',
    'Pikachu("0x54", "Pikachu")',
    'Raichu("0x55", "Raichu")',
    'Dratini("0x58", "Dratini")',
    'Dragonair("0x59", "Dragonair")',
    'Kabuto("0x5A", "Kabuto")',
    'Kabutops("0x5B", "Kabutops")',
    'Horsea("0x5C", "Horsea")',
    'Seadra("0x5D", "Seadra")',
    'Sandshrew("0x60", "Sandshrew")',
    'Sandslash("0x61", "Sandslash")',
    'Omanyte("0x62", "Omanyte")',
    'Omastar("0x63", "Omastar")',
    'Jigglypuff("0x64", "Jigglypuff")',
    'Wigglytuff("0x65", "Wigglytuff")',
    'Eevee("0x66", "Eevee")',
    'Flareon("0x67", "Flareon")',
    'Jolteon("0x68", "Jolteon")',
    'Vaporeon("0x69", "Vaporeon")',
    'Machop("0x6A", "Machop")',
    'Zubat("0x6B", "Zubat")',
    'Ekans("0x6C", "Ekans")',
    'Paras("0x6D", "Paras")',
    'Poliwhirl("0x6E", "Poliwhirl")',
    'Poliwrath("0x6F", "Poliwrath")',
    'Weedle("0x70", "Weedle")',
    'Kakuna("0x71", "Kakuna")',
    'Beedrill("0x72", "Beedrill")',
    'Dodrio("0x74", "Dodrio")',
    'Primeape("0x75", "Primeape")',
    'Dugtrio("0x76", "Dugtrio")',
    'Venomoth("0x77", "Venomoth")',
    'Dewgong("0x78", "Dewgong")',
    'Caterpie("0x7B", "Caterpie")',
    'Metapod("0x7C", "Metapod")',
    'Butterfree("0x7D", "Butterfree")',
    'Machamp("0x7E", "Machamp")',
    'Golduck("0x80", "Golduck")',
    'Hypno("0x81", "Hypno")',
    'Golbat("0x82", "Golbat")',
    'Mewtwo("0x83", "Mewtwo")',
    'Snorlax("0x84", "Snorlax")',
    'Magikarp("0x85", "Magikarp")',
    'Muk("0x88", "Muk")',
    'Kingler("0x8A", "Kingler")',
    'Cloyster("0x8B", "Cloyster")',
    'Electrode("0x8D", "Electrode")',
    'Clefable("0x8E", "Clefable")',
    'Weezing("0x8F", "Weezing")',
    'Persian("0x90", "Persian")',
    'Marowak("0x91", "Marowak")',
    'Haunter("0x93", "Haunter")',
    'Abra("0x94", "Abra")',
    'Alakazam("0x95", "Alakazam")',
    'Pidgeotto("0x96", "Pidgeotto")',
    'Pidgeot("0x97", "Pidgeot")',
    'Starmie("0x98", "Starmie")',
    'Bulbasaur("0x99", "Bulbasaur")',
    'Venusaur("0x9A", "Venusaur")',
    'Tentacruel("0x9B", "Tentacruel")',
    'Goldeen("0x9D", "Goldeen")',
    'Seaking("0x9E", "Seaking")',
    'Ponyta("0xA3", "Ponyta")',
    'Rapidash("0xA4", "Rapidash")',
    'Rattata("0xA5", "Rattata")',
    'Raticate("0xA6", "Raticate")',
    'Nidorino("0xA7", "Nidorino")',
    'Nidorina("0xA8", "Nidorina")',
    'Geodude("0xA9", "Geodude")',
    'Porygon("0xAA", "Porygon")',
    'Aerodactyl("0xAB", "Aerodactyl")',
    'Magnemite("0xAD", "Magnemite")',
    'Charmander("0xB0", "Charmander")',
    'Squirtle("0xB1", "Squirtle")',
    'Charmeleon("0xB2", "Charmeleon")',
    'Wartortle("0xB3", "Wartortle")',
    'Charizard("0xB4", "Charizard")',
    'Oddish("0xB9", "Oddish")',
    'Gloom("0xBA", "Gloom")',
    'Vileplume("0xBB", "Vileplume")',
    'Bellsprout("0xBC", "Bellsprout")',
    'Weepinbell("0xBD", "Weepinbell")',
    'Victreebel("0xBE", "Victreebel");'
]

input4 = [
    'None("0x00", "None"),',
    'Asleep("0x04", "Asleep"),',
    'Poisoned("0x08", "Poisoned"),',
    'Burned("0x10", "Burned"),',
    'Frozen("0x20", "Frozen"),',
    'Paralyzed("0x40", "Paralyzed")'
]

input5 = [
    'Normal("0x00", "Normal"),',
    'Fighting("0x01", "Fighting"),',
    'Flying("0x02", "Flying"),',
    'Poison("0x03", "Poison"),',
    'Ground("0x04", "Ground"),',
    'Rock("0x05", "Rock"),',
    'Bug("0x07", "Bug"),',
    'Ghost("0x08", "Ghost"),',
    'Fire("0x14", "Fire"),',
    'Water("0x15", "Water"),',
    'Grass("0x16", "Grass"),',
    'Electric("0x17", "Electric"),',
    'Psychic("0x18", "Psychic"),',
    'Ice("0x19", "Ice"),',
    'Dragon("0x1A", "Dragon")'
]

input6 = [
"1	Pound	Normal	Physical	Tough	35	40	100%	I",
"2	KarateChop*	Fighting	Physical	Tough	25	50	100%	I",
"3	DoubleSlap	Normal	Physical	Cute	10	15	85%	I",
"4	CometPunch	Normal	Physical	Tough	15	18	85%	I",
"5	MegaPunch	Normal	Physical	Tough	20	80	85%	I",
"6	PayDay	Normal	Physical	Clever	20	40	100%	I",
"7	FirePunch	Fire	Physical	Tough	15	75	100%	I",
"8	IcePunch	Ice	Physical	Beautiful	15	75	100%	I",
"9	ThunderPunch	Electric	Physical	Cool	15	75	100%	I",
"10	Scratch	Normal	Physical	Tough	35	40	100%	I",
"11	ViceGrip	Normal	Physical	Tough	30	55	100%	I",
"12	Guillotine	Normal	Physical	Cool	5	-	-**	I",
"13	RazorWind	Normal	Special	Cool	10	80	100%*	I",
"14	SwordsDance	Normal	Status	Beautiful	20*	-	-	I",
"15	Cut	Normal	Physical	Cool	30	50	95%	I",
"16	Gust*	Flying	Special	Clever	35	40	100%	I",
"17	WingAttack	Flying	Physical	Cool	35	60*	100%	I",
"18	Whirlwind	Normal	Status	Clever	20	-	-*	I",
"19	Fly	Flying	Physical	Clever	15	90*	95%	I",
"20	Bind	Normal	Physical	Tough	20	15	85%*	I",
"21	Slam	Normal	Physical	Tough	20	80	75%	I",
"22	VineWhip	Grass	Physical	Cool	25*	45*	100%	I",
"23	Stomp	Normal	Physical	Tough	20	65	100%	I",
"24	DoubleKick	Fighting	Physical	Cool	30	30	100%	I",
"25	MegaKick	Normal	Physical	Cool	5	120	75%	I",
"26	JumpKick	Fighting	Physical	Cool	10*	100*	95%	I",
"27	RollingKick	Fighting	Physical	Cool	15	60	85%	I",
"28	SandAttack*	Ground	Status	Cute	15	-	100%	I",
"29	Headbutt	Normal	Physical	Tough	15	70	100%	I",
"30	HornAttack	Normal	Physical	Cool	25	65	100%	I",
"31	FuryAttack	Normal	Physical	Cool	20	15	85%	I",
"32	HornDrill	Normal	Physical	Cool	5	-	-**	I",
"33	Tackle	Normal	Physical	Tough	35	40*	100%*	I",
"34	BodySlam	Normal	Physical	Tough	15	85	100%	I",
"35	Wrap	Normal	Physical	Tough	20	15	90%*	I",
"36	TakeDown	Normal	Physical	Tough	20	90	85%	I",
"37	Thrash	Normal	Physical	Tough	10*	120*	100%	I",
"38	Double-Edge	Normal	Physical	Tough	15	120*	100%	I",
"39	TailWhip	Normal	Status	Cute	30	-	100%	I",
"40	PoisonSting	Poison	Physical	Clever	35	15	100%	I",
"41	Twineedle	Bug	Physical	Cool	20	25	100%	I",
"42	PinMissile	Bug	Physical	Cool	20	25*	95%*	I",
"43	Leer	Normal	Status	Cool	30	-	100%	I",
"44	Bite*	Dark	Physical	Tough	25	60	100%	I",
"45	Growl	Normal	Status	Cute	40	-	100%	I",
"46	Roar	Normal	Status	Cool	20	-	-*	I",
"47	Sing	Normal	Status	Cute	15	-	55%	I",
"48	Supersonic	Normal	Status	Clever	20	-	55%	I",
"49	SonicBoom	Normal	Special	Cool	20	*	90%	I",
"50	Disable	Normal	Status	Clever	20	-	100%*	I",
"51	Acid	Poison	Special	Clever	30	40	100%	I",
"52	Ember	Fire	Special	Cute	25	40	100%	I",
"53	Flamethrower	Fire	Special	Beautiful	15	90*	100%	I",
"54	Mist	Ice	Status	Beautiful	30	-	-	I",
"55	WaterGun	Water	Special	Cute	25	40	100%	I",
"56	HydroPump	Water	Special	Beautiful	5	110*	80%	I",
"57	Surf	Water	Special	Beautiful	15	90*	100%	I",
"58	IceBeam	Ice	Special	Beautiful	10	90*	100%	I",
"59	Blizzard	Ice	Special	Beautiful	5	110*	70%*	I",
"60	Psybeam	Psychic	Special	Beautiful	20	65	100%	I",
"61	BubbleBeam	Water	Special	Beautiful	20	65	100%	I",
"62	AuroraBeam	Ice	Special	Beautiful	20	65	100%	I",
"63	HyperBeam	Normal	Special	Cool	5	150	90%	I",
"64	Peck	Flying	Physical	Cool	35	35	100%	I",
"65	DrillPeck	Flying	Physical	Cool	20	80	100%	I",
"66	Submission	Fighting	Physical	Cool	20*	80	80%	I",
"67	LowKick	Fighting	Physical	Tough	20	-*	100%*	I",
"68	Counter	Fighting	Physical	Tough	20	-	100%	I",
"69	SeismicToss	Fighting	Physical	Tough	20	-	100%	I",
"70	Strength	Normal	Physical	Tough	15	80	100%	I",
"71	Absorb	Grass	Special	Clever	25*	20	100%	I",
"72	MegaDrain	Grass	Special	Clever	15*	40	100%	I",
"73	LeechSeed	Grass	Status	Clever	10	-	90%	I",
"74	Growth	Normal	Status	Beautiful	20*	-	-	I",
"75	RazorLeaf	Grass	Physical	Cool	25	55	95%	I",
"76	SolarBeam	Grass	Special	Cool	10	120	100%	I",
"77	PoisonPowder	Poison	Status	Clever	35	-	75%	I",
"78	StunSpore	Grass	Status	Clever	30	-	75%	I",
"79	SleepPowder	Grass	Status	Clever	15	-	75%	I",
"80	PetalDance	Grass	Special	Beautiful	10*	120*	100%	I",
"81	StringShot	Bug	Status	Clever	40	-	95%	I",
"82	DragonRage	Dragon	Special	Cool	10	*	100%	I",
"83	FireSpin	Fire	Special	Beautiful	15	35*	85%*	I",
"84	ThunderShock	Electric	Special	Cool	30	40	100%	I",
"85	Thunderbolt	Electric	Special	Cool	15	90*	100%	I",
"86	ThunderWave	Electric	Status	Cool	20	-	90%*	I",
"87	Thunder	Electric	Special	Cool	10	110*	70%	I",
"88	RockThrow	Rock	Physical	Tough	15	50	90%*	I",
"89	Earthquake	Ground	Physical	Tough	10	100	100%	I",
"90	Fissure	Ground	Physical	Tough	5	-	-**	I",
"91	Dig	Ground	Physical	Tough	10	80*	100%	I",
"92	Toxic	Poison	Status	Clever	10	-	90%*	I",
"93	Confusion	Psychic	Special	Clever	25	50	100%	I",
"94	Psychic	Psychic	Special	Clever	10	90	100%	I",
"95	Hypnosis	Psychic	Status	Clever	20	-	60%*	I",
"96	Meditate	Psychic	Status	Beautiful	40	-	-	I",
"97	Agility	Psychic	Status	Cool	30	-	-	I",
"98	QuickAttack	Normal	Physical	Cool	30	40	100%	I",
"99	Rage	Normal	Physical	Tough	20	20	100%	I",
"100	Teleport	Psychic	Status	Cool	20	-	-	I",
"101	NightShade	Ghost	Special	Clever	15	-	100%	I",
"102	Mimic	Normal	Status	Cute	10	-	-*	I",
"103	Screech	Normal	Status	Clever	40	-	85%	I",
"104	DoubleTeam	Normal	Status	Cool	15	-	-	I",
"105	Recover	Normal	Status	Clever	10*	-	-	I",
"106	Harden	Normal	Status	Tough	30	-	-	I",
"107	Minimize	Normal	Status	Cute	10*	-	-	I",
"108	Smokescreen	Normal	Status	Clever	20	-	100%	I",
"109	ConfuseRay	Ghost	Status	Clever	10	-	100%	I",
"110	Withdraw	Water	Status	Cute	40	-	-	I",
"111	DefenseCurl	Normal	Status	Cute	40	-	-	I",
"112	Barrier	Psychic	Status	Cool	20*	-	-	I",
"113	LightScreen	Psychic	Status	Beautiful	30	-	-	I",
"114	Haze	Ice	Status	Beautiful	30	-	-	I",
"115	Reflect	Psychic	Status	Clever	20	-	-	I",
"116	FocusEnergy	Normal	Status	Cool	30	-	-	I",
"117	Bide	Normal	Physical	Tough	10	-	-*	I",
"118	Metronome	Normal	Status	Cute	10	-	-	I",
"119	MirrorMove	Flying	Status	Clever	20	-	-	I",
"120	Self-Destruct	Normal	Physical	Beautiful	5	200*	100%	I",
"121	EggBomb	Normal	Physical	Cute	10	100	75%	I",
"122	Lick	Ghost	Physical	Cute	30	30*	100%	I",
"123	Smog	Poison	Special	Tough	20	30*	70%	I",
"124	Sludge	Poison	Special	Tough	20	65	100%	I",
"125	BoneClub	Ground	Physical	Tough	20	65	85%	I",
"126	FireBlast	Fire	Special	Beautiful	5	110*	85%	I",
"127	Waterfall	Water	Physical	Tough	15	80	100%	I",
"128	Clamp	Water	Physical	Tough	15*	35	85%*	I",
"129	Swift	Normal	Special	Cool	20	60	-	I",
"130	SkullBash	Normal	Physical	Tough	10*	130*	100%	I",
"131	SpikeCannon	Normal	Physical	Cool	15	20	100%	I",
"132	Constrict	Normal	Physical	Tough	35	10	100%	I",
"133	Amnesia	Psychic	Status	Cute	20	-	-	I",
"134	Kinesis	Psychic	Status	Clever	15	-	80%	I",
"135	Soft-Boiled	Normal	Status	Cute	10	-	-	I",
"136	HighJumpKick	Fighting	Physical	Cool	10*	130*	90%	I",
"137	Glare	Normal	Status	Tough	30	-	100%*	I",
"138	DreamEater	Psychic	Special	Clever	15	100	100%	I",
"139	PoisonGas	Poison	Status	Clever	40	-	90%*	I",
"140	Barrage	Normal	Physical	Cute	20	15	85%	I",
"141	LeechLife	Bug	Physical	Clever	10*	80*	100%	I",
"142	LovelyKiss	Normal	Status	Beautiful	10	-	75%	I",
"143	SkyAttack	Flying	Physical	Cool	5	140	90%	I",
"144	Transform	Normal	Status	Clever	10	-	-	I",
"145	Bubble	Water	Special	Cute	30	40*	100%	I",
"146	DizzyPunch	Normal	Physical	Cute	10	70	100%	I",
"147	Spore	Grass	Status	Beautiful	15	-	100%	I",
"148	Flash	Normal	Status	Beautiful	20	-	100%*	I",
"149	Psywave	Psychic	Special	Clever	15	-	100%*	I",
"150	Splash	Normal	Status	Cute	40	-	-	I",
"151	AcidArmor	Poison	Status	Tough	20*	-	-	I",
"152	Crabhammer	Water	Physical	Tough	10	100*	90%*	I",
"153	Explosion	Normal	Physical	Beautiful	5	250*	100%	I",
"154	FurySwipes	Normal	Physical	Tough	15	18	80%	I",
"155	Bonemerang	Ground	Physical	Tough	10	50	90%	I",
"156	Rest	Psychic	Status	Cute	10	-	-	I",
"157	RockSlide	Rock	Physical	Tough	10	75	90%	I",
"158	HyperFang	Normal	Physical	Cool	15	80	90%	I",
"159	Sharpen	Normal	Status	Cute	30	-	-	I",
"160	Conversion	Normal	Status	Beautiful	30	-	-	I",
"161	TriAttack	Normal	Special	Beautiful	10	80	100%	I",
"162	SuperFang	Normal	Physical	Tough	10	-	90%	I",
"163	Slash	Normal	Physical	Cool	20	70	100%	I",
"164	Substitute	Normal	Status	Cute	10	-	-	I",
"165	Struggle	Normal	Physical	Tough	1*	50	-*	I"
]

def convert(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

def convert_to_space_title(name):
    items = re.findall('[A-Z][^A-Z]*', name)
    return " ".join(items)

def get_contents(line):
    list = re.findall('''"[^"]+"''', line)
    return (list[0][1:-1], list[1])


for item in input6:
    parts = item.split('\t')
    name = convert_to_space_title(parts[1])
    converted_name = convert(parts[1])

    id = parts[0]
    type = parts[2].upper()
    base = parts[3].upper()
    power = parts[6].replace("-", "0")
    accuracy = parts[7].replace("%", "").replace("-", "0")

    out = "Move." + converted_name + " =  Move(\"" + name + "\", " + id +  ", Type." + type + ", MoveBase." + base + ", " + power + ", " + accuracy + ", \"--\")"
    print out
